module.exports = `
    type Dive {
        _id: String
        datum: String
        locatie: String
        temperatuur: Int
        diepte: Float
        buddy: String
        luchtStart: Int
        luchtEind: Int
        user: User!
    }

    type Query {
        allDives: [Dive]
        dive(_id:String!):Dive
        allUsers: [User]
    }

    type User {
        _id: String
        name: String
        email: String!
        jwt: String
        dives: [Dive]!
  }

    type Mutation {
        addDive(
            datum: String
            locatie: String
            temperatuur: Int
            diepte: Float
            buddy: String
            luchtStart: Int
            luchtEind: Int
        ):Dive
        login(email: String!, password: String!):User
        register(email: String!, password: String!,name: String!,):User
        deleteDive(
      _id: String!
    ): Dive
    }
    scalar Date
`