module.exports = `

    scalar Date

    type Dive {
        _id: String
        datum: String
        locatie: String
        temperatuur: Int
        diepte: Float
        buddy: String
        luchtStart: Int
        luchtEind: Int
        user: User 
    }

    type User {
    _id: String
    name: String
    email: String!
    authid: String
    dives: [Dive]
  }

    type Query {
        allDives(user: String): [Dive]
        allUsers: [User]
        dive(_id:String!):Dive
        user(authid:String!):User
    }

    type Mutation {
        addDive(
            datum: String
            locatie: String
            temperatuur: Int
            diepte: Float
            buddy: String
            luchtStart: Int
            luchtEind: Int
        ):Dive
        deleteDive(
      _id: String!
    ): Dive
    register(
      email:String!, 
      authid: String!,
      name:String!,
    ):User
    login(email:String!, password:String! ):User
    }
`